### ISSUE TITLE
There’s an empty translucent dark bar on ornament preview

### ISSUE THREAD

**Issue by floatingatoll** [NigelHietala/ishtar-bugs#444]
Near the bottom of the preview image, there's a translucent dark bar showing.

![image](https://user-images.githubusercontent.com/92684/129488453-6c144abd-b6df-4234-8e5b-cec3d67ece74.jpeg)

**Comment by NigelHietala** [comment]
That is intentional. It 'fakes' the same dark bar that destiny has. When that isn't there the screenshots look weird to me. It is the same reason I put the fake 'weapon ornament' text in the screenshots. They then read at a glance like the game. Even if on careful looking things suddenly don't make sense.
