### ISSUE TITLE
Glaive Descriptions have new placeholder text that needs to be replaced

### ISSUE THREAD

**Issue by andyschott** [NigelHietala/ishtar-bugs#483]
In the Intrinsic Traits, `[Aim Down Sights]` and `[Melee`] need to be replaced.
![IMG_0766](https://user-images.githubusercontent.com/3392920/155230533-5c946cf9-45dc-4f97-b135-23b04ee1577f.PNG)

**Comment by NigelBreslaw** [comment]
I guess the issue issue is replaced with what? I do know what platform the user is playing on so maybe could show the default key or button as an icon for ADS or Melee

**Comment by andyschott** [comment]
That's a good point - I hadn't considered that. I just remembered that in general the other placeholder texts are replaced, but those are all using in-game icons that are consistent across platforms.

**Comment by netniV** [comment]
Maybe Aim Down Sights shows a crosshair? Melee shows a fist?

**Comment by floatingatoll** [comment]
This problem would, theoretically, also exist for Super descriptions, where it says [Heavy Attack] and [Light Attack]. Those probably aren't replaceable because they're 'commands' that vary per-user and per-platform now, so the API and the Ishtar client have no way to see what command is correct, much less whether to use the PC or Console commands from my account were Ishtar to even try to load those prefs (which I suspect aren't in the public API). Sparrows use [Brake] and [Movement] for these as well. I think it's fine not to replace them, and I would far prefer [Aim Down Sights] over an icon that isn't used in-game.

**Comment by andyschott** [comment]
That all seems reasonable to me. So probably best to just leave this as-is then. I'm going to close this issue.
